### PR TITLE
Added Documentation

### LINKED ISSUE #9: Provide a Good Documentation
##  Documentation
Provide a good documentation, so that it can attract and users can read properly

### PR DESCRIPTION
**Pull request by Priyanshu-official**
This PR... #9 
Added Good Documentation
## Changes :factory:

-

## Screenshots :camera:
ScreenShot1

(prefer animated gif)

## Checklist :dart:

- [ ] tested locally
- [ ] added new dependencies
- [x] updated the docs
- [ ] added a test

Fixes #9

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@abhisheknaiidu Pls Review My PR

**Comment by Priyanshu-official** [comment]
@abhisheknaiidu Any update Please

**Review by abhisheknaiidu — APPROVED** [review]
Looks Good for now

**Comment by Priyanshu-official** [comment]
@abhisheknaiidu Thank You

**Pull request merged**
